name: Kaniko release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  determine-version:
    name: Determine Semantic Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "ikasikovic@yahoo.com"
          git config --global user.name "kasikovicivana"

      - name: Determine version
        id: version
        run: |
          VERSION=$(./determine_version.sh "$(git log --pretty=%B -n 1)")
          echo "::set-output name=VERSION::$VERSION"
  build:
    name: Build and test
    runs-on: ubuntu-latest

    needs: determine-version

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      working-directory: ./reservation-service
      run: mvn clean package -DskipTests

    - name: Test app
      working-directory: ./reservation-service
      run: mvn test
    
    - name: Kaniko build
      uses: aevea/action-kaniko@master
      with:
        image: ftndevops2024/reservation-service-example:${{ needs.determine-version.outputs.VERSION }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        cache_registry: aevea/cache