name: Kaniko release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  determine-version:
    name: Determine Semantic Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
      artifact_id: ${{ github.run_id }}-version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "ikasikovic@yahoo.com"
          git config --global user.name "kasikovicivana"

      - name: Set execute permission on script
        run: chmod +x ./scripts/determine_version.sh

      - name: Download version.txt artifact
        uses: actions/download-artifact@v2
        with:
          name: version
          path: version.txt
        continue-on-error: true

      - name: Determine version
        id: version
        run: |
          if [ -f version.txt ]; then
            PREVIOUS_VERSION=$(cat version.txt)
            echo "Previous version: $PREVIOUS_VERSION"
          else
            echo "version.txt not found. Setting default version..."
            PREVIOUS_VERSION="1.0.0"
          fi
          echo "Prev version: $PREVIOUS_VERSION"

          VERSION=$(./scripts/determine_version.sh "${PREVIOUS_VERSION}")

          echo "${VERSION}" > version.txt
          echo "::set-output name=version::$VERSION"
          echo "Determined versiona: $VERSION"

      - name: Upload version.txt as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt

  build:
    name: Build, test and release to Docker Hub
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download version.txt artifact
        uses: actions/download-artifact@v2
        with:
          name: version
          path: ./version.txt

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./reservation-service
        run: mvn clean package -DskipTests

      - name: Test app
        working-directory: ./reservation-service
        run: mvn test

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ftndevops2024/reservation-service-example
          tag: ${{ needs.determine-version.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
