name: Kaniko release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag'
        required: true
        default: '0.1.0'
jobs:
  build:
    name: Build, test and release to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./reservation-service
        run: mvn clean package -DskipTests

      - name: Test app
        working-directory: ./reservation-service
        run: mvn test
      - name: Generate Release Notes
        id: notes
        uses: RedCrafter07/release-notes-action@v1
        with:
          tag-name: ${{ github.event.inputs.releaseTag }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ftndevops2024/reservation-service-example
          tag: ${{ github.event.inputs.releaseTag }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
