name: Kaniko release

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  determine-version:
    name: Determine Semantic Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "ikasikovic@yahoo.com"
          git config --global user.name "kasikovicivana"

      - name: Set execute permission on script
        run: chmod +x ./scripts/determine_version.sh

      - name: Cache version.txt
        uses: actions/cache@v2
        with:
          path: version.txt

      - name: Determine version
        id: version
        run: |
          if [ -f version.txt ]; then
            PREVIOUS_VERSION=$(cat version.txt)
            echo "Previous version: $PREVIOUS_VERSION"
          else
            echo "version.txt not found. Setting default version..."
            PREVIOUS_VERSION="0.0.0"
          fi
          echo "Prev version: $PREVIOUS_VERSION"
          VERSION=$(./scripts/determine_version.sh "${PREVIOUS_VERSION}")
          echo "${VERSION}" > version.txt
          CONTENT=$(cat version.txt)
          echo "Previousaa version: $CONTENT"
          echo "::set-output name=version::$VERSION"
          echo "Determined version: $VERSION"

  build:
    name: Build, test and release to Docker Hub
    runs-on: ubuntu-latest

    needs: determine-version

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        working-directory: ./reservation-service
        run: mvn clean package -DskipTests

      - name: Test app
        working-directory: ./reservation-service
        run: mvn test

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: ftndevops2024/reservation-service-example
          tag: ${{ needs.determine-version.outputs.version }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          cache_registry: aevea/cache
